# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
workflows:
  build-and-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: master


orbs:
  python: circleci/python@2.0.3
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.7.4
    steps:
      - checkout
      - run:
          name: upgrade_pip
          command: |
            pip install --upgrade pip
      - run:
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            python -m unittest discover
  deploy:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: upgrade_pip
          command: |
            pip install --upgrade pip
      - run:
          command: |
            pip install -r requirements.txt
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = whitew1994" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages and upload to pypi
          command: |
            python setup.py sdist
            twine upload dist/*


